# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AlbertaLoop_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1213, 846)
        Dialog.setStyleSheet("background-color: rgb(22, 93, 24);")
        self.HyperLoopPicture = QtWidgets.QLabel(Dialog)
        self.HyperLoopPicture.setGeometry(QtCore.QRect(500, 0, 461, 841))
        self.HyperLoopPicture.setText("")
        self.HyperLoopPicture.setPixmap(QtGui.QPixmap("../Desktop/train-top-view-vector-14357147.jpg"))
        self.HyperLoopPicture.setScaledContents(True)
        self.HyperLoopPicture.setObjectName("HyperLoopPicture")
        self.LeftFrame = QtWidgets.QFrame(Dialog)
        self.LeftFrame.setGeometry(QtCore.QRect(0, 0, 501, 881))
        self.LeftFrame.setMaximumSize(QtCore.QSize(501, 881))
        self.LeftFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LeftFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LeftFrame.setObjectName("LeftFrame")
        self.Speed = QtWidgets.QLabel(self.LeftFrame)
        self.Speed.setGeometry(QtCore.QRect(20, 40, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Speed.setFont(font)
        self.Speed.setStyleSheet("color: rgb(255, 255, 255);")
        self.Speed.setObjectName("Speed")
        self.SpeedEdit = QtWidgets.QLineEdit(self.LeftFrame)
        self.SpeedEdit.setGeometry(QtCore.QRect(120, 50, 71, 31))
        self.SpeedEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SpeedEdit.setObjectName("SpeedEdit")
        self.SpeedUnit = QtWidgets.QLabel(self.LeftFrame)
        self.SpeedUnit.setGeometry(QtCore.QRect(200, 50, 59, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.SpeedUnit.setFont(font)
        self.SpeedUnit.setStyleSheet("color: rgb(255, 255, 255);")
        self.SpeedUnit.setObjectName("SpeedUnit")
        self.Position = QtWidgets.QLabel(self.LeftFrame)
        self.Position.setGeometry(QtCore.QRect(20, 130, 71, 16))
        self.Position.setStyleSheet("color: rgb(255, 255, 255);")
        self.Position.setObjectName("Position")
        self.PositionEdit = QtWidgets.QLineEdit(self.LeftFrame)
        self.PositionEdit.setGeometry(QtCore.QRect(120, 130, 71, 21))
        self.PositionEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PositionEdit.setObjectName("PositionEdit")
        self.Position_Unit = QtWidgets.QLabel(self.LeftFrame)
        self.Position_Unit.setGeometry(QtCore.QRect(200, 130, 16, 16))
        self.Position_Unit.setStyleSheet("color: rgb(255, 255, 255);")
        self.Position_Unit.setObjectName("Position_Unit")
        self.TimeElapsed = QtWidgets.QLabel(self.LeftFrame)
        self.TimeElapsed.setGeometry(QtCore.QRect(20, 200, 91, 20))
        self.TimeElapsed.setStyleSheet("color: rgb(255, 255, 255);")
        self.TimeElapsed.setObjectName("TimeElapsed")
        self.TimeEdit = QtWidgets.QLineEdit(self.LeftFrame)
        self.TimeEdit.setGeometry(QtCore.QRect(120, 200, 71, 21))
        self.TimeEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TimeEdit.setObjectName("TimeEdit")
        self.EstimatedProgress = QtWidgets.QLabel(self.LeftFrame)
        self.EstimatedProgress.setGeometry(QtCore.QRect(20, 250, 151, 20))
        self.EstimatedProgress.setStyleSheet("color: rgb(255, 255, 255);")
        self.EstimatedProgress.setObjectName("EstimatedProgress")
        self.DistanceEdit = QtWidgets.QSlider(self.LeftFrame)
        self.DistanceEdit.setGeometry(QtCore.QRect(20, 280, 281, 22))
        self.DistanceEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DistanceEdit.setOrientation(QtCore.Qt.Horizontal)
        self.DistanceEdit.setObjectName("DistanceEdit")
        self.CommandEdit = QtWidgets.QLineEdit(self.LeftFrame)
        self.CommandEdit.setGeometry(QtCore.QRect(20, 350, 281, 61))
        self.CommandEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 24pt \".SF NS Text\";")
        self.CommandEdit.setObjectName("CommandEdit")
        self.SendCommand = QtWidgets.QPushButton(self.LeftFrame)
        self.SendCommand.setGeometry(QtCore.QRect(320, 350, 151, 61))
        self.SendCommand.setObjectName("SendCommand")
        self.CameraSelection = QtWidgets.QComboBox(self.LeftFrame)
        self.CameraSelection.setGeometry(QtCore.QRect(20, 450, 141, 32))
        self.CameraSelection.setObjectName("CameraSelection")
        self.CameraSelection.addItem("")
        self.CameraSelection.addItem("")
        self.QVideoWidget = QtWidgets.QFrame(self.LeftFrame)
        self.QVideoWidget.setGeometry(QtCore.QRect(20, 490, 431, 321))
        self.QVideoWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QVideoWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.QVideoWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.QVideoWidget.setObjectName("QVideoWidget")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(960, 0, 261, 851))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Battery_1 = QtWidgets.QLabel(self.frame)
        self.Battery_1.setGeometry(QtCore.QRect(10, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Battery_1.setFont(font)
        self.Battery_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.Battery_1.setObjectName("Battery_1")
        self.Temperature_1 = QtWidgets.QLabel(self.frame)
        self.Temperature_1.setGeometry(QtCore.QRect(10, 40, 91, 20))
        self.Temperature_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.Temperature_1.setObjectName("Temperature_1")
        self.TemperatureEdit_1 = QtWidgets.QLineEdit(self.frame)
        self.TemperatureEdit_1.setGeometry(QtCore.QRect(120, 40, 71, 21))
        self.TemperatureEdit_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TemperatureEdit_1.setObjectName("TemperatureEdit_1")
        self.Voltage_1 = QtWidgets.QLabel(self.frame)
        self.Voltage_1.setGeometry(QtCore.QRect(10, 60, 59, 16))
        self.Voltage_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.Voltage_1.setObjectName("Voltage_1")
        self.VoltageEdit_1 = QtWidgets.QLineEdit(self.frame)
        self.VoltageEdit_1.setGeometry(QtCore.QRect(120, 60, 71, 21))
        self.VoltageEdit_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.VoltageEdit_1.setObjectName("VoltageEdit_1")
        self.Battery_2 = QtWidgets.QLabel(self.frame)
        self.Battery_2.setGeometry(QtCore.QRect(10, 120, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Battery_2.setFont(font)
        self.Battery_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.Battery_2.setObjectName("Battery_2")
        self.Temperature_2 = QtWidgets.QLabel(self.frame)
        self.Temperature_2.setGeometry(QtCore.QRect(10, 150, 91, 16))
        self.Temperature_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.Temperature_2.setObjectName("Temperature_2")
        self.TemperatureEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.TemperatureEdit_2.setGeometry(QtCore.QRect(120, 150, 71, 21))
        self.TemperatureEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TemperatureEdit_2.setObjectName("TemperatureEdit_2")
        self.Voltage_2 = QtWidgets.QLabel(self.frame)
        self.Voltage_2.setGeometry(QtCore.QRect(10, 170, 59, 21))
        self.Voltage_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.Voltage_2.setObjectName("Voltage_2")
        self.VoltageEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.VoltageEdit_2.setGeometry(QtCore.QRect(120, 170, 71, 21))
        self.VoltageEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.VoltageEdit_2.setObjectName("VoltageEdit_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Speed.setText(_translate("Dialog", "SPEED"))
        self.SpeedUnit.setText(_translate("Dialog", "Km/h"))
        self.Position.setText(_translate("Dialog", "POSITION"))
        self.Position_Unit.setText(_translate("Dialog", "m"))
        self.TimeElapsed.setText(_translate("Dialog", "TIME ELAPSED"))
        self.EstimatedProgress.setText(_translate("Dialog", "ESTIMATED PROGRESS"))
        self.CommandEdit.setText(_translate("Dialog", "Type command here"))
        self.SendCommand.setText(_translate("Dialog", "SEND"))
        self.CameraSelection.setItemText(0, _translate("Dialog", "Front Camera"))
        self.CameraSelection.setItemText(1, _translate("Dialog", "Rear Camera"))
        self.Battery_1.setText(_translate("Dialog", "BATTERY 1"))
        self.Temperature_1.setText(_translate("Dialog", "TEMPERATURE"))
        self.Voltage_1.setText(_translate("Dialog", "VOLTAGE"))
        self.Battery_2.setText(_translate("Dialog", "BATTERY 2"))
        self.Temperature_2.setText(_translate("Dialog", "TEMPERATURE"))
        self.Voltage_2.setText(_translate("Dialog", "VOLTAGE"))
        import sys
        from PyQt5 import QtWidgets as qtw
        from PyQt5 import QtGui as qtg
        from PyQt5 import QtCore as qtc


        from PyQt5 import QtCore, QtGui, QtWidgets, QtMultimedia

        from GUI import Ui_MainWindow

        class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
            def __init__(self, *args, **kwargs):
                QtWidgets.QMainWindow.__init__(self, *args, **kwargs)
                self.setupUi(self)

                self.mediaPlayer = QtMultimedia.QMediaPlayer(self)
                self.mediaPlayer.setVideoOutput(self.widget)
                # fileName = "/path/of/your/local_file"
                # url = QtCore.QUrl.fromLocalFile(fileName)
                url = QtCore.QUrl("http://clips.vorwaerts-gmbh.de/VfE_html5.mp4")
                self.mediaPlayer.setMedia(QtMultimedia.QMediaContent(url))
                self.mediaPlayer.play()

        if __name__ == "__main__":
            import sys
            app = QtWidgets.QApplication(sys.argv)
            w = MainWindow()
            w.show()
            sys.exit(app.exec_())


        class MainWindow(qtw.QWidget):
                    def __init__(self):
                        super().__init__()
                        self.show()
        if __name__ == '__main__':
                        app = qtw.QApplication(sys.argv)
                        mw = MainWindow()
                        sys.exit(app.exec())
